<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>err_FieldPhone</name>
   <tag></tag>
   <elementGuidId>c8732734-2c57-45de-8141-b43d8151ddd1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div/div[1]/div/div/div/div[2]/div/div/div[2]/form/div/div[2]/div/div/small/i</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//i[@class = 'text-danger']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>2230566f-e081-427d-89fe-b767c79a9387</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-danger</value>
      <webElementGuid>6c7c7856-056c-46fc-a8e3-0b2578f10a9d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
