<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_REGISTER_re-retype-password</name>
   <tag></tag>
   <elementGuidId>45d427e8-4885-47bf-9f12-1d35c35d31d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#re-retype-password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='re-retype-password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2cd63adc-6e59-4744-b9f5-7fb11031b15d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>re-retype-password</value>
      <webElementGuid>ba30ae85-2d3c-42f6-a072-a9f738b34c12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>re-retype-password</value>
      <webElementGuid>a00291b3-ae77-446c-ac07-51fdd83349f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>CONFIRM PASSWORD</value>
      <webElementGuid>13296f42-def1-45fe-b460-a0eb178b3930</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>90ec2c80-2c05-4238-a259-298d4e8375c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>FormRePassword__Style-sc-1s7xcl0-0 ivumoT form-control</value>
      <webElementGuid>c71313c3-1684-4c10-8bf3-5ab581bd78c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;re-retype-password&quot;)</value>
      <webElementGuid>c3c3a929-5dcf-44df-880c-f581097e0fad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='re-retype-password']</value>
      <webElementGuid>1742cceb-8ad1-4e11-af1b-b1c78ebe426d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/div/div/input</value>
      <webElementGuid>b3ef2447-1ee7-405f-a994-127bcc1b2b37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 're-retype-password' and @id = 're-retype-password' and @placeholder = 'CONFIRM PASSWORD' and @type = 'password']</value>
      <webElementGuid>48945c4a-effa-469f-a05b-271217fe6cba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
