<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_REGISTER_Fullname</name>
   <tag></tag>
   <elementGuidId>74554e9b-f8fa-463e-afbb-a2615114e615</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Fullname</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Fullname']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6b0dd5c4-7d77-4688-935a-783bf90d83fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Fullname</value>
      <webElementGuid>8569bd77-e18f-421a-9769-d86435edce22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Fullname</value>
      <webElementGuid>c29c0075-9487-4af5-b71e-42114feee491</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>FULLNAME</value>
      <webElementGuid>9328ac75-dcad-43e6-8a9d-75afbe5fde1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7cf0f3c3-7256-48eb-81fa-c6e7fa68c74d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>FormText__Style-rslcf2-0 jZbfmf form-control</value>
      <webElementGuid>aa39352c-406d-449f-8f0a-1c02810e3b2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Fullname&quot;)</value>
      <webElementGuid>d227b435-3045-4d4e-86bc-fd20d04cc7f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Fullname']</value>
      <webElementGuid>bb26150b-1cd6-4b49-9305-5fda25f3ac3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/input</value>
      <webElementGuid>e57e160c-727c-49ea-a5c4-9ff6880e1ffe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'Fullname' and @id = 'Fullname' and @placeholder = 'FULLNAME' and @type = 'text']</value>
      <webElementGuid>c64a90fc-1824-426f-ad97-bc1c5364d1f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
