<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rect</name>
   <tag></tag>
   <elementGuidId>6e12af71-ff25-4d75-bc27-342fc6b6793a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Icon_User_Log_In_White > g > rect</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'Icon_User_Log_In_White']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>rect</value>
      <webElementGuid>bfeb8dee-a7e8-41f0-84ab-940c6150ebf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>b80d4bd2-9491-47ef-91e7-b649d80591e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>9823ef66-93e9-499f-a94b-1d7588dd6eec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Icon_User_Log_In_White&quot;)/g[1]/rect[1]</value>
      <webElementGuid>b99961e1-deaf-42af-b15e-925676e9c207</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Icon_User_Log_In_White</value>
      <webElementGuid>40172a3a-984f-466a-89fa-318a153279fb</webElementGuid>
   </webElementProperties>
</WebElementEntity>
